#!/usr/bin/env python3
"""Public copy rules for every lab README (labs/**/README.md).

Fails the build on:
  - an em dash (U+2014) or en dash (U+2013)
  - Claude or Anthropic, except in labs/capstone-2, and there only in a paragraph that names Amazon Bedrock
    (the model the lab runs); an AI credit ("Claude Code", "written with", "generated by", ChatGPT, Copilot)
    fails everywhere
  - hiring or job-search wording (the same list the studio portal uses for YouTube and LinkedIn copy). A bare
    "job" is left alone because the labs build scheduled and CI jobs.

Usage: readme-guard.py [ROOT]   (ROOT defaults to the repo root; it scans ROOT/labs/**/README.md)
"""
import re
import sys
from pathlib import Path

DASHES = re.compile("[\u2013\u2014]")
MODEL_NAMES = re.compile(r"\b(claude|anthropic)\b", re.I)
# A Bedrock model id (anthropic.claude-..., us.anthropic.claude-...) is a resource name, not a mention.
MODEL_ID = re.compile(r"\b(?:[a-z]{2}\.)?anthropic\.claude[\w.:-]*", re.I)
AI_CREDIT = re.compile(
    r"\b(claude code|chatgpt|gpt-\d|copilot|co-authored-by|(written|generated|created|made|built) (with|by|using) "
    r"(ai|an ai|claude|chatgpt|copilot|anthropic|openai))\b", re.I)
JOB_WORDS = re.compile(
    r"\b(hire|hires|hired|hiring|recruiter|recruiters|recruiting|recruitment|job[- ]search(?:ing)?|job[- ]hunt(?:ing)?|"
    r"interview|interviews|interviewing|interviewer|resume|resumes|r[\u00e9e]sum[\u00e9e]s?|open to work|employer|"
    r"employers|employment|career change|looking for (?:a |my next )?(?:role|position|work|opportunity))\b", re.I)
JOB_SEARCH = re.compile(
    r"\b((new|dream|next|first|full[- ]time|part[- ]time|remote|entry[- ]level|tech|cloud|devops|it)\s+jobs?|"
    r"(land(ed|ing)?|get(ting)?|find(ing)?|apply(ing)?\s+(for|to)|want(ed)?|need(ed)?)\s+(an?\s+|the\s+|my\s+)?jobs?|"
    r"jobs?\s+(offers?|market|postings?|seekers?|titles?|applications?|boards?|listings?|hunt(ing)?|search(ing)?|"
    r"openings?|opportunit(y|ies)))\b", re.I)
CAPSTONE_2 = "capstone-2"


def paragraphs(text):
    """(first line number, paragraph text) for each blank-line separated block."""
    start, buf = 1, []
    for n, line in enumerate(text.splitlines() + [""], 1):
        if line.strip():
            if not buf:
                start = n
            buf.append(line)
        elif buf:
            yield start, "\n".join(buf)
            buf = []


def check(path, lab):
    problems = []
    text = path.read_text(encoding="utf-8")
    for n, line in enumerate(text.splitlines(), 1):
        if DASHES.search(line):
            problems.append((n, "em or en dash (use a comma, colon or hyphen)"))
        for m in AI_CREDIT.finditer(line):
            problems.append((n, f'AI credit "{m.group(0)}"'))
        for rx in (JOB_WORDS, JOB_SEARCH):
            for m in rx.finditer(line):
                problems.append((n, f'job-search wording "{m.group(0)}"'))
    for start, para in paragraphs(text):
        bare = MODEL_ID.sub("", para)
        hits = MODEL_NAMES.findall(bare)
        if not hits:
            continue
        if lab == CAPSTONE_2 and re.search(r"\bbedrock\b", para, re.I):
            continue
        where = "outside capstone-2" if lab != CAPSTONE_2 else "in a paragraph that doesn't name Amazon Bedrock"
        problems.append((start, f"mentions {hits[0]} {where}"))
    return problems


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    readmes = sorted((root / "labs").glob("**/README.md"))
    failed = 0
    for p in readmes:
        rel = p.relative_to(root)
        lab = rel.parts[1] if len(rel.parts) > 2 else ""
        for n, msg in check(p, lab):
            failed += 1
            print(f"::error file={rel},line={n}::{msg}")
            print(f"{rel}:{n}: {msg}", file=sys.stderr)
    print(f"{len(readmes)} lab READMEs checked, {failed} problems")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
